services:
    app:
        build: .
        container_name: crud
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - laravel_net
        command: sh -c "composer install && php artisan migrate --force && php artisan db:seed --class=ProdutosSeeder && php-fpm"

    db:
        image: mysql:8
        container_name: mysql-db
        environment:
            MYSQL_DATABASE: crud
            MYSQL_USER: laravel
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        networks:
            - laravel_net

    nginx:
        image: nginx:stable-alpine
        container_name: nginx-server
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        ports:
            - "8080:80"
        networks:
            - laravel_net

networks:
    laravel_net:
        driver: bridge
